#!/usr/bin/env bash
# Regenerate the `orbit init` packaging of this demo.
#
# `orbit init` syncs environment-source repositories, and that sync only
# copies envs/**/*.yaml plus envs/seeds/** into the local cache. This script
# derives envs/quickstart.yaml from the project-root orbit.yaml and mirrors
# the application into envs/seeds/mini-shop so both entry points — cloning
# this repo and running the bundled quickstart — run the exact same shop.
#
# CI regenerates and fails on any diff, so edit apps/ and orbit.yaml only,
# then run this script.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
seeds="$root/envs/seeds/mini-shop"

rm -rf "$seeds"
mkdir -p "$seeds"
cp "$root"/apps/*.py "$root"/apps/*.html "$seeds/"
cp "$root/scripts/smoke.py" "$seeds/"

{
  printf '# Generated by scripts/sync-quickstart.sh — do not edit.\n'
  printf '# The same environment as ../orbit.yaml, packaged for `orbit init`:\n'
  printf '# the sync that backs environment sources ships envs/seeds/**, so the\n'
  printf '# app runs from envs/seeds/mini-shop (a byte-for-byte copy of apps/).\n'
  sed 's|path: ./apps|path: seeds/mini-shop|' "$root/orbit.yaml"
} > "$root/envs/quickstart.yaml"

echo "quickstart packaging regenerated"
